---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-apikey-secret
  namespace: kube-system
type: Opaque
stringData:
  email: yourcloudflareemail@example.com
  apiKey: yourCloudflareApiToken
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik-config.yaml: |
    http:
      middlewares:
        headers-default:
          headers:
            sslRedirect: true
            browserXssFilter: true
            contentTypeNosniff: true
            forceSTSHeader: true
            stsIncludeSubdomains: true
            stsPreload: true
            stsSeconds: 15552000
            customFrameOptionsValue: SAMEORIGIN
            customRequestHeaders:
              X-Forwarded-Proto: https
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-json-certs
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteMany # I needed both for rw
  - ReadWriteOnce # I needed both for rw
  resources:
    requests:
      storage: 128Mi    